### ISSUE TITLE
Incompatible with Webpack 5

### ISSUE THREAD

**Issue by jwbth** [lcxfs1991/banner-webpack-plugin#4]
The plugin seems to be incompatible with the latest official version of Webpack, 5.31.2.

Using at as a plugin in the following fashion
```
    new BannerWebpackPlugin({
      chunks: {
        main: {
          afterContent: '\n/*! </nowiki> */',
        },
      },
    })
```

results in this error:
```
[webpack-cli] TypeError: compiler.plugin is not a function
    at BannerWebpackPlugin.apply ([...]\node_modules\banner-webpack-plugin\index.js:16:14)
    at createCompiler ([...]\node_modules\webpack\lib\webpack.js:71:12)
    at create ([...]\node_modules\webpack\lib\webpack.js:118:16)
    at webpack ([...]\node_modules\webpack\lib\webpack.js:126:47)
    at WebpackCLI.f [as webpack] ([...]\node_modules\webpack\lib\index.js:54:15)
    at WebpackCLI.createCompiler ([...]\node_modules\webpack-cli\lib\webpack-cli.js:1847:29)
    at async WebpackCLI.buildCommand ([...]\node_modules\webpack-cli\lib\webpack-cli.js:1954:20)
    at async Command.<anonymous> ([...]\node_modules\webpack-cli\lib\webpack-cli.js:735:25)
    at async Promise.all (index 1)
    at async Command.<anonymous> ([...]\node_modules\webpack-cli\lib\webpack-cli.js:1284:13)
```

It's OK with Webpack 4.

**Comment by imarksea** [comment]
i have resolved
